language: node_js
node_js:
  - "6"
install:
  - npm install -g yarn
  - yarn
cache:
  directories:
    - ~/.yarn-cache
    - ~/.nvm
script:
  - yarn test:ci
deploy:
  provider: script
  script: yarn run deploy -- -t $NETLIFY_TOKEN
