language: node_js
node_js:
- '6'
install:
- npm install -g yarn
- yarn
cache:
  directories:
  - "~/.yarn-cache"
  - "~/.nvm"
script:
- yarn test:ci
deploy:
  provider: script
  skip_cleanup: true
  script: yarn run deploy -- -t $NETLIFY_TOKEN
  on:
    branch: master
branches:
  only:
  - master
notifications:
  email: false
  slack:
    on_pull_requests: false
    secure: kSwhXRxaKtrmpJNJVtGfqz2Rb6Y1/ICbFVPLYwDRLhaJe76Pm+nEy6yvluBPXwh52VvDpwxEPw4NiQEgIIB7Drcy0wEVQ1aOF9Arhd/bJHR4z4JgoXTKSpfwZte4AWFclVB6x86kyevT03+Yo58tRSgo8BPXTiYKvoYEn1qCZz06eQv8sw91K5TCeGIVA6Xl3HajgW8BjV1gwdHxa5kqwRefERzVVr210Y3j1NqBlbwukFYtroxknzGJrJbWPIGSiY426Bn6c1f5ZFnZm6H/TK1qYldQKeTrh6E5TkTXuNxJaKSibuD4OeLEcXl+AxFg9aJDRnZ5+Q9S5yPdy7Wzd7usOlWofBg16uNooMwLpIzsiNqUapP0nJZdBLjACEe15nYRA7bqj8xG9WuZlPP8RCBkbRT9OyD5A8kqqOEEnZBxn07mJt4rjfxa8ZzWWd8StNGm8QjrZUCWj+wVnF7LlqHgcMZHGFurWQ2MdLhITn5tZgoAFVAhMtPsygUCiNT82KWFMPTbSMregEExoAjF9dgY7fYs7MEmyTmXqBcnAji9bdUsrLgMXM7H6CL6xq7ztIRXPIFXGU82n3QwELSiVtQEB1zD08owjaDFJUaXFI5298wq+KoN55J8eGVDLtl6zFvWCe22NyGqKBAg5GxwJYCw0PKxXCxtnhrVZrKPK5Q=
