siteTitle = "Кузница мобильных решений | Anvilabs"
siteDescription = "Anvilabs - Проектируем и разрабатываем инновационные мобильные и веб приложения. (Алматы, Казахстан)"
analyticsKey = "VFrFyZj4WjHK96OwBAlTECvAQhC6jQDS"
contactEmail = "info@anvilabs.co"
hostname = "https://anvilabs.co"
mailchimpActionUrl = "//yenbekbay.us11.list-manage.com/subscribe/post?u=983b78ee49621c4871e7a16ea&amp;id=0da8d3b335"


[[menuLinks]]
  to = "/work/"
  title = "Работы"

[[menuLinks]]
  to = "/about/"
  title = "О нас"

[[menuLinks]]
  to = "/blog/"
  title = "Блог"

[[menuLinks]]
  to = "/contact/"
  title = "Контакты"


[[footerLinks]]
  href = "https://twitter.com/anvilabs"
  title = "Twitter"

[[footerLinks]]
  href = "https://facebook.com/anvilabs"
  title = "Facebook"

[[footerLinks]]
  href = "https://github.com/anvilabs"
  title = "Github"

[[footerLinks]]
  href = "https://medium.com/anvilabs"
  title = "Medium"
