// flow-typed signature: c956b558e30a0fdb9f451c6b87a8a383
// flow-typed version: <<STUB>>/@types/autobind-decorator_v^1.3.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/autobind-decorator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/autobind-decorator' {
  declare module.exports: any;
}
