// flow-typed signature: 6a4df10226e0302c512550267bd55545
// flow-typed version: <<STUB>>/@types/axios_v^0.9.32/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/axios' {
  declare module.exports: any;
}
