// flow-typed signature: e14b7d573a83f9d5459ed443cd89b7c4
// flow-typed version: <<STUB>>/@types/axios_v^0.9.34/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/axios'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/axios' {
  declare module.exports: any;
}
