// flow-typed signature: 133a2b1a70af1a5ef906f9e8b292f87c
// flow-typed version: <<STUB>>/@types/cheerio_v^0.17.31/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/cheerio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/cheerio' {
  declare module.exports: any;
}
