// flow-typed signature: f69ff771260d626eaa43e3b37ff38fc8
// flow-typed version: <<STUB>>/@types/cheerio_v^0.17.31/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/cheerio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/cheerio' {
  declare module.exports: any;
}
