// flow-typed signature: 011ff0a3d62062418e302d02e9c18b17
// flow-typed version: <<STUB>>/@types/chokidar_v^1.4.29/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chokidar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chokidar' {
  declare module.exports: any;
}
