// flow-typed signature: 67030070c23164bd35816b1a7cadfabc
// flow-typed version: <<STUB>>/@types/chokidar_v^1.4.30/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chokidar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chokidar' {
  declare module.exports: any;
}
