// flow-typed signature: 5c6eb654369073c9466a3b82a5ec148c
// flow-typed version: <<STUB>>/@types/classnames_v^0.0.31/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/classnames'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/classnames' {
  declare module.exports: any;
}
