// flow-typed signature: 1b1c2971858c9110bd9ce4f752197d15
// flow-typed version: <<STUB>>/@types/classnames_v^0.0.32/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/classnames'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/classnames' {
  declare module.exports: any;
}
