// flow-typed signature: 40c037c9d264cfa9d0b132ba572fdeba
// flow-typed version: <<STUB>>/@types/fs-extra_v^0.0.33/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/fs-extra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/fs-extra' {
  declare module.exports: any;
}
