// flow-typed signature: b7b6b183108ff52becc39901a74be013
// flow-typed version: <<STUB>>/@types/glob_v^5.0.30/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/glob'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/glob' {
  declare module.exports: any;
}
