// flow-typed signature: 7ddfe187c336809e348019a5dd67bb78
// flow-typed version: <<STUB>>/@types/gulp_v^3.8.32/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/gulp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/gulp' {
  declare module.exports: any;
}
