// flow-typed signature: 6defefe8714ddbae22c0d96e44293ffd
// flow-typed version: <<STUB>>/@types/highlight.js_v^9.1.8/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/highlight.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/highlight.js' {
  declare module.exports: any;
}
