// flow-typed signature: 471b6cdd4c4abc2b6d8527a6d456fe4e
// flow-typed version: <<STUB>>/@types/inquirer_v^0.0.29/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/inquirer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/inquirer' {
  declare module.exports: any;
}
