// flow-typed signature: 949acb9b0dd5c94554c96d5f977c3096
// flow-typed version: <<STUB>>/@types/js-yaml_v^3.5.28/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/js-yaml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/js-yaml' {
  declare module.exports: any;
}
