// flow-typed signature: 4cba2d77676106b4c95ed226ada5e105
// flow-typed version: <<STUB>>/@types/mkdirp_v^0.3.29/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mkdirp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mkdirp' {
  declare module.exports: any;
}
