// flow-typed signature: fea6c4b985b2a1264514fec7da0747e2
// flow-typed version: <<STUB>>/@types/moment_v^2.13.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/moment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/moment' {
  declare module.exports: any;
}
