// flow-typed signature: 818d99809f1a1f2d848048adf46093f0
// flow-typed version: <<STUB>>/@types/open_v^0.0.29/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/open'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/open' {
  declare module.exports: any;
}
