// flow-typed signature: dde175634c653a90c68ce5a25a31d19a
// flow-typed version: <<STUB>>/@types/react-router_v^2.0.38/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-router' {
  declare module.exports: any;
}
