// flow-typed signature: bc374de8239e77a05bc6616c1b9c84bc
// flow-typed version: <<STUB>>/@types/react-router_v^2.0.41/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-router' {
  declare module.exports: any;
}
