// flow-typed signature: 698adcced6b3fd55977d3adce77bae07
// flow-typed version: <<STUB>>/@types/rss_v^0.0.27/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/rss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/rss' {
  declare module.exports: any;
}
