// flow-typed signature: dce34521aad991563b24f4dc285ee0f8
// flow-typed version: <<STUB>>/@types/striptags_v^0.0.5/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/striptags'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/striptags' {
  declare module.exports: any;
}
