// flow-typed signature: 45cb98ca4a508ec440d5faf1b0f8e936
// flow-typed version: <<STUB>>/absolutify_v^0.1.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'absolutify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'absolutify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'absolutify/140' {
  declare module.exports: any;
}

declare module 'absolutify/140.min' {
  declare module.exports: any;
}

declare module 'absolutify/absolutify' {
  declare module.exports: any;
}

declare module 'absolutify/absolutify.min' {
  declare module.exports: any;
}

declare module 'absolutify/test' {
  declare module.exports: any;
}

declare module 'absolutify/tmp/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'absolutify/140.js' {
  declare module.exports: $Exports<'absolutify/140'>;
}
declare module 'absolutify/140.min.js' {
  declare module.exports: $Exports<'absolutify/140.min'>;
}
declare module 'absolutify/absolutify.js' {
  declare module.exports: $Exports<'absolutify/absolutify'>;
}
declare module 'absolutify/absolutify.min.js' {
  declare module.exports: $Exports<'absolutify/absolutify.min'>;
}
declare module 'absolutify/test.js' {
  declare module.exports: $Exports<'absolutify/test'>;
}
declare module 'absolutify/tmp/test.js' {
  declare module.exports: $Exports<'absolutify/tmp/test'>;
}
