// flow-typed signature: 244648626a965aa83489dc3229b2d827
// flow-typed version: <<STUB>>/babel-plugin-flow-react-proptypes_v^0.14.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-flow-react-proptypes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-flow-react-proptypes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/array-shorthand.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/array-shorthand.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/basic.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/basic.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/children.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/children.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-named.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-named.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-non-object-types.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-non-object-types.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-object.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-object.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/function-types.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/function-types.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/import-object.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/import-object.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/issue-14.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/issue-14.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/just-exports.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/just-exports.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/literal-type-annotation.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/literal-type-annotation.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/no-type.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/no-type.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/nullable.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/nullable.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/real.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/real.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/stateless.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/stateless.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/typeof.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/typeof.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/convertToPropTypes' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/makePropTypesAst' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/lib/util' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/array-shorthand.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/array-shorthand.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/basic.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/basic.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/children.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/children.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/class-and-function.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/class-and-function.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/class-inline-props.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/class-inline-props.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/exact-syntax.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/exact-syntax.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/exact.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/exact.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-named.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-named.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-non-object-types.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-non-object-types.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-object.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-object.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-type-and-component.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-type-and-component.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/function-types.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/function-types.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/import-and-loops.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/import-and-loops.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/import-object.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/import-object.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/intersection.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/intersection.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/just-exports.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/just-exports.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/literal-type-annotation.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/literal-type-annotation.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/no-type.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/no-type.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/nullable.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/nullable.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/object-props.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/object-props.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/real.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/real.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow-body-without-jsx.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow-body-without-jsx.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow-body.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow-body.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-exports.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-exports.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline-defaults.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline-defaults.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline-imports.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline-imports.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-without-jsx.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-without-jsx.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/suppress.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/suppress.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/tupletype.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/tupletype.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/typeof.input' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/typeof.output' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/convertToPropTypes' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/index' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/makePropTypesAst' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/src/util' {
  declare module.exports: any;
}

declare module 'babel-plugin-flow-react-proptypes/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/array-shorthand.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/array-shorthand.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/array-shorthand.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/array-shorthand.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/basic.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/basic.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/basic.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/basic.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/children.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/children.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/children.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/children.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-named.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-named.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-named.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-named.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-non-object-types.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-non-object-types.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-non-object-types.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-non-object-types.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-object.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-object.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-object.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/export-object.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/function-types.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/function-types.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/function-types.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/function-types.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/import-object.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/import-object.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/import-object.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/import-object.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/issue-14.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/issue-14.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/issue-14.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/issue-14.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/just-exports.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/just-exports.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/just-exports.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/just-exports.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/literal-type-annotation.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/literal-type-annotation.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/literal-type-annotation.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/literal-type-annotation.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/no-type.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/no-type.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/no-type.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/no-type.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/nullable.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/nullable.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/nullable.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/nullable.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/real.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/real.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/real.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/real.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/stateless.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/stateless.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/stateless.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/stateless.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/typeof.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/typeof.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/typeof.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/__test__/fixtures/typeof.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/convertToPropTypes.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/convertToPropTypes'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/index'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/makePropTypesAst.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/makePropTypesAst'>;
}
declare module 'babel-plugin-flow-react-proptypes/lib/util.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/lib/util'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/array-shorthand.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/array-shorthand.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/array-shorthand.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/array-shorthand.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/basic.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/basic.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/basic.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/basic.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/children.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/children.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/children.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/children.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/class-and-function.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/class-and-function.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/class-and-function.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/class-and-function.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/class-inline-props.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/class-inline-props.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/class-inline-props.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/class-inline-props.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/exact-syntax.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/exact-syntax.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/exact-syntax.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/exact-syntax.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/exact.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/exact.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/exact.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/exact.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-named.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-named.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-named.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-named.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-non-object-types.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-non-object-types.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-non-object-types.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-non-object-types.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-object.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-object.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-object.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-object.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-type-and-component.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-type-and-component.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-type-and-component.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/export-type-and-component.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/function-types.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/function-types.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/function-types.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/function-types.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/import-and-loops.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/import-and-loops.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/import-and-loops.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/import-and-loops.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/import-object.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/import-object.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/import-object.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/import-object.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/intersection.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/intersection.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/intersection.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/intersection.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/just-exports.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/just-exports.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/just-exports.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/just-exports.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/literal-type-annotation.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/literal-type-annotation.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/literal-type-annotation.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/literal-type-annotation.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/no-type.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/no-type.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/no-type.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/no-type.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/nullable.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/nullable.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/nullable.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/nullable.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/object-props.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/object-props.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/object-props.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/object-props.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/real.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/real.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/real.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/real.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow-body-without-jsx.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow-body-without-jsx.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow-body-without-jsx.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow-body-without-jsx.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow-body.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow-body.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow-body.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow-body.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-arrow.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-exports.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-exports.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-exports.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-exports.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline-defaults.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline-defaults.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline-defaults.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline-defaults.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline-imports.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline-imports.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline-imports.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline-imports.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-inline.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-without-jsx.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-without-jsx.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-without-jsx.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless-without-jsx.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/stateless.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/suppress.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/suppress.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/suppress.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/suppress.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/tupletype.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/tupletype.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/tupletype.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/tupletype.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/typeof.input.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/typeof.input'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/__test__/fixtures/typeof.output.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/__test__/fixtures/typeof.output'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/convertToPropTypes.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/convertToPropTypes'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/index.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/index'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/makePropTypesAst.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/makePropTypesAst'>;
}
declare module 'babel-plugin-flow-react-proptypes/src/util.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/src/util'>;
}
declare module 'babel-plugin-flow-react-proptypes/test/index.js' {
  declare module.exports: $Exports<'babel-plugin-flow-react-proptypes/test/index'>;
}
