// flow-typed signature: 658b3df5be63cef809769bacdb4a865f
// flow-typed version: <<STUB>>/excerpt-html_v^1.2.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'excerpt-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'excerpt-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'excerpt-html/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'excerpt-html/index' {
  declare module.exports: $Exports<'excerpt-html'>;
}
declare module 'excerpt-html/index.js' {
  declare module.exports: $Exports<'excerpt-html'>;
}
declare module 'excerpt-html/test/index.js' {
  declare module.exports: $Exports<'excerpt-html/test/index'>;
}
