// flow-typed signature: dbf7b74b8983b1ee5889ff3d0aa05045
// flow-typed version: <<STUB>>/gatsby_v^0.12.14/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby/bin/gatsby' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bin/cli' {
  declare module.exports: any;
}

declare module 'gatsby/dist/bin/published' {
  declare module.exports: any;
}

declare module 'gatsby/dist/isomorphic/create-routes' {
  declare module.exports: any;
}

declare module 'gatsby/dist/isomorphic/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby/dist/isomorphic/gatsby-helpers' {
  declare module.exports: any;
}

declare module 'gatsby/dist/isomorphic/html' {
  declare module.exports: any;
}

declare module 'gatsby/dist/isomorphic/pages/_template' {
  declare module.exports: any;
}

declare module 'gatsby/dist/isomorphic/wrappers/html' {
  declare module.exports: any;
}

declare module 'gatsby/dist/isomorphic/wrappers/md' {
  declare module.exports: any;
}

declare module 'gatsby/dist/loaders/config-loader/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/loaders/html-loader/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/loaders/markdown-loader/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/babel-config' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/build-css' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/build-html' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/build-javascript' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/build-page/index' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/build-page/load-frontmatter' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/build-page/path-resolver' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/build-page/url-resolver' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/build' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/develop' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/glob-pages' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/init-starter' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/load-context' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/new' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/page-file-types' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/post-build' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/serve-build' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/web-entry' {
  declare module.exports: any;
}

declare module 'gatsby/dist/utils/webpack.config' {
  declare module.exports: any;
}

declare module 'gatsby/interfaces/front-matter' {
  declare module.exports: any;
}

declare module 'gatsby/interfaces/html-frontmatter' {
  declare module.exports: any;
}

declare module 'gatsby/interfaces/invariant' {
  declare module.exports: any;
}

declare module 'gatsby/interfaces/object-assign' {
  declare module.exports: any;
}

declare module 'gatsby/interfaces/parse-filepath' {
  declare module.exports: any;
}

declare module 'gatsby/interfaces/slash' {
  declare module.exports: any;
}

declare module 'gatsby/lib/bin/cli' {
  declare module.exports: any;
}

declare module 'gatsby/lib/bin/published' {
  declare module.exports: any;
}

declare module 'gatsby/lib/isomorphic/create-routes' {
  declare module.exports: any;
}

declare module 'gatsby/lib/isomorphic/gatsby-browser' {
  declare module.exports: any;
}

declare module 'gatsby/lib/isomorphic/gatsby-helpers' {
  declare module.exports: any;
}

declare module 'gatsby/lib/isomorphic/html' {
  declare module.exports: any;
}

declare module 'gatsby/lib/isomorphic/pages/_template' {
  declare module.exports: any;
}

declare module 'gatsby/lib/isomorphic/wrappers/html' {
  declare module.exports: any;
}

declare module 'gatsby/lib/isomorphic/wrappers/md' {
  declare module.exports: any;
}

declare module 'gatsby/lib/loaders/config-loader/index' {
  declare module.exports: any;
}

declare module 'gatsby/lib/loaders/html-loader/index' {
  declare module.exports: any;
}

declare module 'gatsby/lib/loaders/markdown-loader/index' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/babel-config' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/build-css' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/build-html' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/build-javascript' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/build-page/index' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/build-page/load-frontmatter' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/build-page/path-resolver' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/build-page/url-resolver' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/build' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/develop' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/glob-pages' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/init-starter' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/load-context' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/new' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/page-file-types' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/post-build' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/serve-build' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/static-entry' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/web-entry' {
  declare module.exports: any;
}

declare module 'gatsby/lib/utils/webpack.config' {
  declare module.exports: any;
}

declare module 'gatsby/scripts/flow-check' {
  declare module.exports: any;
}

declare module 'gatsby/test/fixtures/path-not-ending-in-slash/public/bundle' {
  declare module.exports: any;
}

declare module 'gatsby/test/fixtures/path-rewrite/gatsby-node' {
  declare module.exports: any;
}

declare module 'gatsby/test/fixtures/path-rewrite/public/bundle' {
  declare module.exports: any;
}

declare module 'gatsby/test/fixtures/static-wrappers/public/bundle' {
  declare module.exports: any;
}

declare module 'gatsby/test/integration/cli-returns-help' {
  declare module.exports: any;
}

declare module 'gatsby/test/integration/install-starter' {
  declare module.exports: any;
}

declare module 'gatsby/test/integration/static-html-wrappers' {
  declare module.exports: any;
}

declare module 'gatsby/test/integration/user-rewrites-path-not-ending-in-slash' {
  declare module.exports: any;
}

declare module 'gatsby/test/integration/user-rewrites-path' {
  declare module.exports: any;
}

declare module 'gatsby/test/support' {
  declare module.exports: any;
}

declare module 'gatsby/test/utils/babel-config' {
  declare module.exports: any;
}

declare module 'gatsby/test/utils/build-page/path-resolver' {
  declare module.exports: any;
}

declare module 'gatsby/test/utils/build-page/url-resolver' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby/bin/gatsby.js' {
  declare module.exports: $Exports<'gatsby/bin/gatsby'>;
}
declare module 'gatsby/dist/bin/cli.js' {
  declare module.exports: $Exports<'gatsby/dist/bin/cli'>;
}
declare module 'gatsby/dist/bin/published.js' {
  declare module.exports: $Exports<'gatsby/dist/bin/published'>;
}
declare module 'gatsby/dist/isomorphic/create-routes.js' {
  declare module.exports: $Exports<'gatsby/dist/isomorphic/create-routes'>;
}
declare module 'gatsby/dist/isomorphic/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby/dist/isomorphic/gatsby-browser'>;
}
declare module 'gatsby/dist/isomorphic/gatsby-helpers.js' {
  declare module.exports: $Exports<'gatsby/dist/isomorphic/gatsby-helpers'>;
}
declare module 'gatsby/dist/isomorphic/html.js' {
  declare module.exports: $Exports<'gatsby/dist/isomorphic/html'>;
}
declare module 'gatsby/dist/isomorphic/pages/_template.js' {
  declare module.exports: $Exports<'gatsby/dist/isomorphic/pages/_template'>;
}
declare module 'gatsby/dist/isomorphic/wrappers/html.js' {
  declare module.exports: $Exports<'gatsby/dist/isomorphic/wrappers/html'>;
}
declare module 'gatsby/dist/isomorphic/wrappers/md.js' {
  declare module.exports: $Exports<'gatsby/dist/isomorphic/wrappers/md'>;
}
declare module 'gatsby/dist/loaders/config-loader/index.js' {
  declare module.exports: $Exports<'gatsby/dist/loaders/config-loader/index'>;
}
declare module 'gatsby/dist/loaders/html-loader/index.js' {
  declare module.exports: $Exports<'gatsby/dist/loaders/html-loader/index'>;
}
declare module 'gatsby/dist/loaders/markdown-loader/index.js' {
  declare module.exports: $Exports<'gatsby/dist/loaders/markdown-loader/index'>;
}
declare module 'gatsby/dist/utils/babel-config.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/babel-config'>;
}
declare module 'gatsby/dist/utils/build-css.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/build-css'>;
}
declare module 'gatsby/dist/utils/build-html.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/build-html'>;
}
declare module 'gatsby/dist/utils/build-javascript.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/build-javascript'>;
}
declare module 'gatsby/dist/utils/build-page/index.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/build-page/index'>;
}
declare module 'gatsby/dist/utils/build-page/load-frontmatter.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/build-page/load-frontmatter'>;
}
declare module 'gatsby/dist/utils/build-page/path-resolver.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/build-page/path-resolver'>;
}
declare module 'gatsby/dist/utils/build-page/url-resolver.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/build-page/url-resolver'>;
}
declare module 'gatsby/dist/utils/build.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/build'>;
}
declare module 'gatsby/dist/utils/develop.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/develop'>;
}
declare module 'gatsby/dist/utils/glob-pages.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/glob-pages'>;
}
declare module 'gatsby/dist/utils/init-starter.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/init-starter'>;
}
declare module 'gatsby/dist/utils/load-context.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/load-context'>;
}
declare module 'gatsby/dist/utils/new.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/new'>;
}
declare module 'gatsby/dist/utils/page-file-types.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/page-file-types'>;
}
declare module 'gatsby/dist/utils/post-build.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/post-build'>;
}
declare module 'gatsby/dist/utils/serve-build.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/serve-build'>;
}
declare module 'gatsby/dist/utils/static-entry.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/static-entry'>;
}
declare module 'gatsby/dist/utils/web-entry.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/web-entry'>;
}
declare module 'gatsby/dist/utils/webpack.config.js' {
  declare module.exports: $Exports<'gatsby/dist/utils/webpack.config'>;
}
declare module 'gatsby/interfaces/front-matter.js' {
  declare module.exports: $Exports<'gatsby/interfaces/front-matter'>;
}
declare module 'gatsby/interfaces/html-frontmatter.js' {
  declare module.exports: $Exports<'gatsby/interfaces/html-frontmatter'>;
}
declare module 'gatsby/interfaces/invariant.js' {
  declare module.exports: $Exports<'gatsby/interfaces/invariant'>;
}
declare module 'gatsby/interfaces/object-assign.js' {
  declare module.exports: $Exports<'gatsby/interfaces/object-assign'>;
}
declare module 'gatsby/interfaces/parse-filepath.js' {
  declare module.exports: $Exports<'gatsby/interfaces/parse-filepath'>;
}
declare module 'gatsby/interfaces/slash.js' {
  declare module.exports: $Exports<'gatsby/interfaces/slash'>;
}
declare module 'gatsby/lib/bin/cli.js' {
  declare module.exports: $Exports<'gatsby/lib/bin/cli'>;
}
declare module 'gatsby/lib/bin/published.js' {
  declare module.exports: $Exports<'gatsby/lib/bin/published'>;
}
declare module 'gatsby/lib/isomorphic/create-routes.js' {
  declare module.exports: $Exports<'gatsby/lib/isomorphic/create-routes'>;
}
declare module 'gatsby/lib/isomorphic/gatsby-browser.js' {
  declare module.exports: $Exports<'gatsby/lib/isomorphic/gatsby-browser'>;
}
declare module 'gatsby/lib/isomorphic/gatsby-helpers.js' {
  declare module.exports: $Exports<'gatsby/lib/isomorphic/gatsby-helpers'>;
}
declare module 'gatsby/lib/isomorphic/html.js' {
  declare module.exports: $Exports<'gatsby/lib/isomorphic/html'>;
}
declare module 'gatsby/lib/isomorphic/pages/_template.js' {
  declare module.exports: $Exports<'gatsby/lib/isomorphic/pages/_template'>;
}
declare module 'gatsby/lib/isomorphic/wrappers/html.js' {
  declare module.exports: $Exports<'gatsby/lib/isomorphic/wrappers/html'>;
}
declare module 'gatsby/lib/isomorphic/wrappers/md.js' {
  declare module.exports: $Exports<'gatsby/lib/isomorphic/wrappers/md'>;
}
declare module 'gatsby/lib/loaders/config-loader/index.js' {
  declare module.exports: $Exports<'gatsby/lib/loaders/config-loader/index'>;
}
declare module 'gatsby/lib/loaders/html-loader/index.js' {
  declare module.exports: $Exports<'gatsby/lib/loaders/html-loader/index'>;
}
declare module 'gatsby/lib/loaders/markdown-loader/index.js' {
  declare module.exports: $Exports<'gatsby/lib/loaders/markdown-loader/index'>;
}
declare module 'gatsby/lib/utils/babel-config.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/babel-config'>;
}
declare module 'gatsby/lib/utils/build-css.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/build-css'>;
}
declare module 'gatsby/lib/utils/build-html.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/build-html'>;
}
declare module 'gatsby/lib/utils/build-javascript.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/build-javascript'>;
}
declare module 'gatsby/lib/utils/build-page/index.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/build-page/index'>;
}
declare module 'gatsby/lib/utils/build-page/load-frontmatter.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/build-page/load-frontmatter'>;
}
declare module 'gatsby/lib/utils/build-page/path-resolver.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/build-page/path-resolver'>;
}
declare module 'gatsby/lib/utils/build-page/url-resolver.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/build-page/url-resolver'>;
}
declare module 'gatsby/lib/utils/build.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/build'>;
}
declare module 'gatsby/lib/utils/develop.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/develop'>;
}
declare module 'gatsby/lib/utils/glob-pages.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/glob-pages'>;
}
declare module 'gatsby/lib/utils/init-starter.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/init-starter'>;
}
declare module 'gatsby/lib/utils/load-context.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/load-context'>;
}
declare module 'gatsby/lib/utils/new.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/new'>;
}
declare module 'gatsby/lib/utils/page-file-types.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/page-file-types'>;
}
declare module 'gatsby/lib/utils/post-build.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/post-build'>;
}
declare module 'gatsby/lib/utils/serve-build.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/serve-build'>;
}
declare module 'gatsby/lib/utils/static-entry.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/static-entry'>;
}
declare module 'gatsby/lib/utils/web-entry.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/web-entry'>;
}
declare module 'gatsby/lib/utils/webpack.config.js' {
  declare module.exports: $Exports<'gatsby/lib/utils/webpack.config'>;
}
declare module 'gatsby/scripts/flow-check.js' {
  declare module.exports: $Exports<'gatsby/scripts/flow-check'>;
}
declare module 'gatsby/test/fixtures/path-not-ending-in-slash/public/bundle.js' {
  declare module.exports: $Exports<'gatsby/test/fixtures/path-not-ending-in-slash/public/bundle'>;
}
declare module 'gatsby/test/fixtures/path-rewrite/gatsby-node.js' {
  declare module.exports: $Exports<'gatsby/test/fixtures/path-rewrite/gatsby-node'>;
}
declare module 'gatsby/test/fixtures/path-rewrite/public/bundle.js' {
  declare module.exports: $Exports<'gatsby/test/fixtures/path-rewrite/public/bundle'>;
}
declare module 'gatsby/test/fixtures/static-wrappers/public/bundle.js' {
  declare module.exports: $Exports<'gatsby/test/fixtures/static-wrappers/public/bundle'>;
}
declare module 'gatsby/test/integration/cli-returns-help.js' {
  declare module.exports: $Exports<'gatsby/test/integration/cli-returns-help'>;
}
declare module 'gatsby/test/integration/install-starter.js' {
  declare module.exports: $Exports<'gatsby/test/integration/install-starter'>;
}
declare module 'gatsby/test/integration/static-html-wrappers.js' {
  declare module.exports: $Exports<'gatsby/test/integration/static-html-wrappers'>;
}
declare module 'gatsby/test/integration/user-rewrites-path-not-ending-in-slash.js' {
  declare module.exports: $Exports<'gatsby/test/integration/user-rewrites-path-not-ending-in-slash'>;
}
declare module 'gatsby/test/integration/user-rewrites-path.js' {
  declare module.exports: $Exports<'gatsby/test/integration/user-rewrites-path'>;
}
declare module 'gatsby/test/support.js' {
  declare module.exports: $Exports<'gatsby/test/support'>;
}
declare module 'gatsby/test/utils/babel-config.js' {
  declare module.exports: $Exports<'gatsby/test/utils/babel-config'>;
}
declare module 'gatsby/test/utils/build-page/path-resolver.js' {
  declare module.exports: $Exports<'gatsby/test/utils/build-page/path-resolver'>;
}
declare module 'gatsby/test/utils/build-page/url-resolver.js' {
  declare module.exports: $Exports<'gatsby/test/utils/build-page/url-resolver'>;
}
