// flow-typed signature: 61ea31258b25ccabfb7fd7d883ad1078
// flow-typed version: <<STUB>>/gulp-inline-source_v^3.0.0/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-inline-source'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-inline-source' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-inline-source/test/fixtures/script' {
  declare module.exports: any;
}

declare module 'gulp-inline-source/test/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-inline-source/index' {
  declare module.exports: $Exports<'gulp-inline-source'>;
}
declare module 'gulp-inline-source/index.js' {
  declare module.exports: $Exports<'gulp-inline-source'>;
}
declare module 'gulp-inline-source/test/fixtures/script.js' {
  declare module.exports: $Exports<'gulp-inline-source/test/fixtures/script'>;
}
declare module 'gulp-inline-source/test/main.js' {
  declare module.exports: $Exports<'gulp-inline-source/test/main'>;
}
