// flow-typed signature: 56974f477c6d0a18fce6af86438fc78a
// flow-typed version: <<STUB>>/gulp-cssnano_v^2.1.2/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-cssnano'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-cssnano' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-cssnano/index' {
  declare module.exports: $Exports<'gulp-cssnano'>;
}
declare module 'gulp-cssnano/index.js' {
  declare module.exports: $Exports<'gulp-cssnano'>;
}
