// flow-typed signature: 963bd2823f9cfef8d9e3fa7989685995
// flow-typed version: <<STUB>>/gulp-google-webfonts_v^0.0.14/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-google-webfonts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-google-webfonts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-google-webfonts/example1/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-google-webfonts/example2/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-google-webfonts/example1/gulpfile.js' {
  declare module.exports: $Exports<'gulp-google-webfonts/example1/gulpfile'>;
}
declare module 'gulp-google-webfonts/example2/gulpfile.js' {
  declare module.exports: $Exports<'gulp-google-webfonts/example2/gulpfile'>;
}
declare module 'gulp-google-webfonts/index' {
  declare module.exports: $Exports<'gulp-google-webfonts'>;
}
declare module 'gulp-google-webfonts/index.js' {
  declare module.exports: $Exports<'gulp-google-webfonts'>;
}
