// flow-typed signature: 39451478c3a8a35e3a8ae467fedd39b9
// flow-typed version: <<STUB>>/gulp-minify-inline_v^0.2.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-minify-inline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-minify-inline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-minify-inline/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-minify-inline/index' {
  declare module.exports: $Exports<'gulp-minify-inline'>;
}
declare module 'gulp-minify-inline/index.js' {
  declare module.exports: $Exports<'gulp-minify-inline'>;
}
declare module 'gulp-minify-inline/test/test.js' {
  declare module.exports: $Exports<'gulp-minify-inline/test/test'>;
}
