// flow-typed signature: 40471b83564ba8147b04042e1dcd230f
// flow-typed version: <<STUB>>/gulp-imagemin_v^3.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-imagemin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-imagemin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-imagemin/index' {
  declare module.exports: $Exports<'gulp-imagemin'>;
}
declare module 'gulp-imagemin/index.js' {
  declare module.exports: $Exports<'gulp-imagemin'>;
}
