// flow-typed signature: 0e92dc101398846092968b850c9c67a0
// flow-typed version: <<STUB>>/gulp-uncss_v^1.0.6/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-uncss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-uncss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-uncss/index' {
  declare module.exports: $Exports<'gulp-uncss'>;
}
declare module 'gulp-uncss/index.js' {
  declare module.exports: $Exports<'gulp-uncss'>;
}
