// flow-typed signature: 85addb253653c2d3432749b81912e0ef
// flow-typed version: <<STUB>>/imagemin-optipng_v^5.2.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-optipng'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin-optipng' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'imagemin-optipng/index' {
  declare module.exports: $Exports<'imagemin-optipng'>;
}
declare module 'imagemin-optipng/index.js' {
  declare module.exports: $Exports<'imagemin-optipng'>;
}
