// flow-typed signature: 3285821bd34cc34a3ab58dd7a78bc5cd
// flow-typed version: <<STUB>>/imagemin-jpegtran_v^5.0.2/flow_v0.39.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-jpegtran'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin-jpegtran' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'imagemin-jpegtran/index' {
  declare module.exports: $Exports<'imagemin-jpegtran'>;
}
declare module 'imagemin-jpegtran/index.js' {
  declare module.exports: $Exports<'imagemin-jpegtran'>;
}
