// flow-typed signature: f4f0e43503c66772d9b718187fe53f08
// flow-typed version: <<STUB>>/imagemin-gifsicle_v^5.1.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-gifsicle'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin-gifsicle' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'imagemin-gifsicle/index' {
  declare module.exports: $Exports<'imagemin-gifsicle'>;
}
declare module 'imagemin-gifsicle/index.js' {
  declare module.exports: $Exports<'imagemin-gifsicle'>;
}
