// flow-typed signature: 0404381c05d940f851a7a960f31793a8
// flow-typed version: <<STUB>>/markdown-it-link-attributes_v^1.0.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-it-link-attributes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-it-link-attributes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'markdown-it-link-attributes/index' {
  declare module.exports: $Exports<'markdown-it-link-attributes'>;
}
declare module 'markdown-it-link-attributes/index.js' {
  declare module.exports: $Exports<'markdown-it-link-attributes'>;
}
