// flow-typed signature: 610257896c5c6c5704caa8e088a5cd7c
// flow-typed version: <<STUB>>/markdown-it-implicit-figures_v^0.3.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-it-implicit-figures'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-it-implicit-figures' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-it-implicit-figures/demo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-it-implicit-figures/demo.js' {
  declare module.exports: $Exports<'markdown-it-implicit-figures/demo'>;
}
declare module 'markdown-it-implicit-figures/index' {
  declare module.exports: $Exports<'markdown-it-implicit-figures'>;
}
declare module 'markdown-it-implicit-figures/index.js' {
  declare module.exports: $Exports<'markdown-it-implicit-figures'>;
}
