// flow-typed signature: f64e7d4f77356fe495d7090ee08bc8bf
// flow-typed version: <<STUB>>/markdown-it-attrs_v^0.8.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-it-attrs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-it-attrs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-it-attrs/demo' {
  declare module.exports: any;
}

declare module 'markdown-it-attrs/markdown-it-attrs.browser' {
  declare module.exports: any;
}

declare module 'markdown-it-attrs/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-it-attrs/demo.js' {
  declare module.exports: $Exports<'markdown-it-attrs/demo'>;
}
declare module 'markdown-it-attrs/index' {
  declare module.exports: $Exports<'markdown-it-attrs'>;
}
declare module 'markdown-it-attrs/index.js' {
  declare module.exports: $Exports<'markdown-it-attrs'>;
}
declare module 'markdown-it-attrs/markdown-it-attrs.browser.js' {
  declare module.exports: $Exports<'markdown-it-attrs/markdown-it-attrs.browser'>;
}
declare module 'markdown-it-attrs/utils.js' {
  declare module.exports: $Exports<'markdown-it-attrs/utils'>;
}
