// flow-typed signature: af3b168cd282ef9b593c3358227d635c
// flow-typed version: <<STUB>>/markdown-it-table-of-contents_v^0.3.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-it-table-of-contents'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-it-table-of-contents' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-it-table-of-contents/test/modules/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-it-table-of-contents/index' {
  declare module.exports: $Exports<'markdown-it-table-of-contents'>;
}
declare module 'markdown-it-table-of-contents/index.js' {
  declare module.exports: $Exports<'markdown-it-table-of-contents'>;
}
declare module 'markdown-it-table-of-contents/test/modules/test.js' {
  declare module.exports: $Exports<'markdown-it-table-of-contents/test/modules/test'>;
}
