// flow-typed signature: da195ad947212bb5e8b8da2c59b6ea0a
// flow-typed version: <<STUB>>/markdown-it-footnote_v^3.0.1/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-it-footnote'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-it-footnote' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-it-footnote/dist/markdown-it-footnote' {
  declare module.exports: any;
}

declare module 'markdown-it-footnote/dist/markdown-it-footnote.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-it-footnote/dist/markdown-it-footnote.js' {
  declare module.exports: $Exports<'markdown-it-footnote/dist/markdown-it-footnote'>;
}
declare module 'markdown-it-footnote/dist/markdown-it-footnote.min.js' {
  declare module.exports: $Exports<'markdown-it-footnote/dist/markdown-it-footnote.min'>;
}
declare module 'markdown-it-footnote/index' {
  declare module.exports: $Exports<'markdown-it-footnote'>;
}
declare module 'markdown-it-footnote/index.js' {
  declare module.exports: $Exports<'markdown-it-footnote'>;
}
