// flow-typed signature: 5e3b40095d03ba9481c200513c70b333
// flow-typed version: <<STUB>>/markdown-it-anchor_v^2.5.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-it-anchor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-it-anchor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-it-anchor/demo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-it-anchor/demo.js' {
  declare module.exports: $Exports<'markdown-it-anchor/demo'>;
}
declare module 'markdown-it-anchor/index' {
  declare module.exports: $Exports<'markdown-it-anchor'>;
}
declare module 'markdown-it-anchor/index.js' {
  declare module.exports: $Exports<'markdown-it-anchor'>;
}
