// flow-typed signature: 4ca0d74268132bbae9a43e08b58b073d
// flow-typed version: <<STUB>>/netlify-cli_v^1.1.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'netlify-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'netlify-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'netlify-cli/bin/cli' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/commands/create_site' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/commands/delete_site' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/commands/deploy' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/commands/init' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/commands/init/bitbucket' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/commands/init/github' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/commands/init/manual' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/commands/list_sites' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/commands/open' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/commands/publish' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/commands/ssl' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/commands/update_site' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/helpers/confirm' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/helpers/error_logger' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/helpers/git' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/helpers/site_picker' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/helpers/webui' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/settings/config' {
  declare module.exports: any;
}

declare module 'netlify-cli/lib/settings/webauth' {
  declare module.exports: any;
}

// Filename aliases
declare module 'netlify-cli/bin/cli.js' {
  declare module.exports: $Exports<'netlify-cli/bin/cli'>;
}
declare module 'netlify-cli/lib/commands/create_site.js' {
  declare module.exports: $Exports<'netlify-cli/lib/commands/create_site'>;
}
declare module 'netlify-cli/lib/commands/delete_site.js' {
  declare module.exports: $Exports<'netlify-cli/lib/commands/delete_site'>;
}
declare module 'netlify-cli/lib/commands/deploy.js' {
  declare module.exports: $Exports<'netlify-cli/lib/commands/deploy'>;
}
declare module 'netlify-cli/lib/commands/init.js' {
  declare module.exports: $Exports<'netlify-cli/lib/commands/init'>;
}
declare module 'netlify-cli/lib/commands/init/bitbucket.js' {
  declare module.exports: $Exports<'netlify-cli/lib/commands/init/bitbucket'>;
}
declare module 'netlify-cli/lib/commands/init/github.js' {
  declare module.exports: $Exports<'netlify-cli/lib/commands/init/github'>;
}
declare module 'netlify-cli/lib/commands/init/manual.js' {
  declare module.exports: $Exports<'netlify-cli/lib/commands/init/manual'>;
}
declare module 'netlify-cli/lib/commands/list_sites.js' {
  declare module.exports: $Exports<'netlify-cli/lib/commands/list_sites'>;
}
declare module 'netlify-cli/lib/commands/open.js' {
  declare module.exports: $Exports<'netlify-cli/lib/commands/open'>;
}
declare module 'netlify-cli/lib/commands/publish.js' {
  declare module.exports: $Exports<'netlify-cli/lib/commands/publish'>;
}
declare module 'netlify-cli/lib/commands/ssl.js' {
  declare module.exports: $Exports<'netlify-cli/lib/commands/ssl'>;
}
declare module 'netlify-cli/lib/commands/update_site.js' {
  declare module.exports: $Exports<'netlify-cli/lib/commands/update_site'>;
}
declare module 'netlify-cli/lib/helpers/confirm.js' {
  declare module.exports: $Exports<'netlify-cli/lib/helpers/confirm'>;
}
declare module 'netlify-cli/lib/helpers/error_logger.js' {
  declare module.exports: $Exports<'netlify-cli/lib/helpers/error_logger'>;
}
declare module 'netlify-cli/lib/helpers/git.js' {
  declare module.exports: $Exports<'netlify-cli/lib/helpers/git'>;
}
declare module 'netlify-cli/lib/helpers/site_picker.js' {
  declare module.exports: $Exports<'netlify-cli/lib/helpers/site_picker'>;
}
declare module 'netlify-cli/lib/helpers/webui.js' {
  declare module.exports: $Exports<'netlify-cli/lib/helpers/webui'>;
}
declare module 'netlify-cli/lib/settings/config.js' {
  declare module.exports: $Exports<'netlify-cli/lib/settings/config'>;
}
declare module 'netlify-cli/lib/settings/webauth.js' {
  declare module.exports: $Exports<'netlify-cli/lib/settings/webauth'>;
}
