// flow-typed signature: 62d56dab68d6ca32a38e6d729a21ac55
// flow-typed version: <<STUB>>/netlify_v^1.1.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'netlify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'netlify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'netlify/docs/js/affix' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/bootstrap-affix.min' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/bootstrap-collapse.min' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/bootstrap-dropdown.min' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/bootstrap-scrollspy.min' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/bootstrap-transition.min' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/dropdown' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/index.min' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/jquery.min' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/prism-bash' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/prism-jade' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/prism' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/prism.min' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/scrollspy' {
  declare module.exports: any;
}

declare module 'netlify/docs/js/twitter-widget.min' {
  declare module.exports: any;
}

declare module 'netlify/lib/access-token' {
  declare module.exports: any;
}

declare module 'netlify/lib/client' {
  declare module.exports: any;
}

declare module 'netlify/lib/deploy_key' {
  declare module.exports: any;
}

declare module 'netlify/lib/deploy' {
  declare module.exports: any;
}

declare module 'netlify/lib/dns-record' {
  declare module.exports: any;
}

declare module 'netlify/lib/dns-zone' {
  declare module.exports: any;
}

declare module 'netlify/lib/file' {
  declare module.exports: any;
}

declare module 'netlify/lib/form' {
  declare module.exports: any;
}

declare module 'netlify/lib/model' {
  declare module.exports: any;
}

declare module 'netlify/lib/netlify' {
  declare module.exports: any;
}

declare module 'netlify/lib/site' {
  declare module.exports: any;
}

declare module 'netlify/lib/snippet' {
  declare module.exports: any;
}

declare module 'netlify/lib/submission' {
  declare module.exports: any;
}

declare module 'netlify/lib/ticket' {
  declare module.exports: any;
}

declare module 'netlify/lib/user' {
  declare module.exports: any;
}

declare module 'netlify/spec/netlify.spec' {
  declare module.exports: any;
}

declare module 'netlify/vendor/jasmine/jasmine-html' {
  declare module.exports: any;
}

declare module 'netlify/vendor/jasmine/jasmine' {
  declare module.exports: any;
}

// Filename aliases
declare module 'netlify/docs/js/affix.js' {
  declare module.exports: $Exports<'netlify/docs/js/affix'>;
}
declare module 'netlify/docs/js/bootstrap-affix.min.js' {
  declare module.exports: $Exports<'netlify/docs/js/bootstrap-affix.min'>;
}
declare module 'netlify/docs/js/bootstrap-collapse.min.js' {
  declare module.exports: $Exports<'netlify/docs/js/bootstrap-collapse.min'>;
}
declare module 'netlify/docs/js/bootstrap-dropdown.min.js' {
  declare module.exports: $Exports<'netlify/docs/js/bootstrap-dropdown.min'>;
}
declare module 'netlify/docs/js/bootstrap-scrollspy.min.js' {
  declare module.exports: $Exports<'netlify/docs/js/bootstrap-scrollspy.min'>;
}
declare module 'netlify/docs/js/bootstrap-transition.min.js' {
  declare module.exports: $Exports<'netlify/docs/js/bootstrap-transition.min'>;
}
declare module 'netlify/docs/js/bootstrap.min.js' {
  declare module.exports: $Exports<'netlify/docs/js/bootstrap.min'>;
}
declare module 'netlify/docs/js/dropdown.js' {
  declare module.exports: $Exports<'netlify/docs/js/dropdown'>;
}
declare module 'netlify/docs/js/index.min.js' {
  declare module.exports: $Exports<'netlify/docs/js/index.min'>;
}
declare module 'netlify/docs/js/jquery.min.js' {
  declare module.exports: $Exports<'netlify/docs/js/jquery.min'>;
}
declare module 'netlify/docs/js/prism-bash.js' {
  declare module.exports: $Exports<'netlify/docs/js/prism-bash'>;
}
declare module 'netlify/docs/js/prism-jade.js' {
  declare module.exports: $Exports<'netlify/docs/js/prism-jade'>;
}
declare module 'netlify/docs/js/prism.js' {
  declare module.exports: $Exports<'netlify/docs/js/prism'>;
}
declare module 'netlify/docs/js/prism.min.js' {
  declare module.exports: $Exports<'netlify/docs/js/prism.min'>;
}
declare module 'netlify/docs/js/scrollspy.js' {
  declare module.exports: $Exports<'netlify/docs/js/scrollspy'>;
}
declare module 'netlify/docs/js/twitter-widget.min.js' {
  declare module.exports: $Exports<'netlify/docs/js/twitter-widget.min'>;
}
declare module 'netlify/lib/access-token.js' {
  declare module.exports: $Exports<'netlify/lib/access-token'>;
}
declare module 'netlify/lib/client.js' {
  declare module.exports: $Exports<'netlify/lib/client'>;
}
declare module 'netlify/lib/deploy_key.js' {
  declare module.exports: $Exports<'netlify/lib/deploy_key'>;
}
declare module 'netlify/lib/deploy.js' {
  declare module.exports: $Exports<'netlify/lib/deploy'>;
}
declare module 'netlify/lib/dns-record.js' {
  declare module.exports: $Exports<'netlify/lib/dns-record'>;
}
declare module 'netlify/lib/dns-zone.js' {
  declare module.exports: $Exports<'netlify/lib/dns-zone'>;
}
declare module 'netlify/lib/file.js' {
  declare module.exports: $Exports<'netlify/lib/file'>;
}
declare module 'netlify/lib/form.js' {
  declare module.exports: $Exports<'netlify/lib/form'>;
}
declare module 'netlify/lib/model.js' {
  declare module.exports: $Exports<'netlify/lib/model'>;
}
declare module 'netlify/lib/netlify.js' {
  declare module.exports: $Exports<'netlify/lib/netlify'>;
}
declare module 'netlify/lib/site.js' {
  declare module.exports: $Exports<'netlify/lib/site'>;
}
declare module 'netlify/lib/snippet.js' {
  declare module.exports: $Exports<'netlify/lib/snippet'>;
}
declare module 'netlify/lib/submission.js' {
  declare module.exports: $Exports<'netlify/lib/submission'>;
}
declare module 'netlify/lib/ticket.js' {
  declare module.exports: $Exports<'netlify/lib/ticket'>;
}
declare module 'netlify/lib/user.js' {
  declare module.exports: $Exports<'netlify/lib/user'>;
}
declare module 'netlify/spec/netlify.spec.js' {
  declare module.exports: $Exports<'netlify/spec/netlify.spec'>;
}
declare module 'netlify/vendor/jasmine/jasmine-html.js' {
  declare module.exports: $Exports<'netlify/vendor/jasmine/jasmine-html'>;
}
declare module 'netlify/vendor/jasmine/jasmine.js' {
  declare module.exports: $Exports<'netlify/vendor/jasmine/jasmine'>;
}
