// flow-typed signature: 79af277a7c7a576c625356ce56cf17fa
// flow-typed version: <<STUB>>/pageres_v^4.2.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pageres'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'pageres' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pageres/dist/index' {
  declare module.exports: any;
}

declare module 'pageres/dist/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pageres/dist/index.js' {
  declare module.exports: $Exports<'pageres/dist/index'>;
}
declare module 'pageres/dist/util.js' {
  declare module.exports: $Exports<'pageres/dist/util'>;
}
