// flow-typed signature: 82935fc7b612d41c1d27e76a6928e364
// flow-typed version: <<STUB>>/plural-ru_v^1.1.1/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plural-ru'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'plural-ru' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'plural-ru/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'plural-ru/index' {
  declare module.exports: $Exports<'plural-ru'>;
}
declare module 'plural-ru/index.js' {
  declare module.exports: $Exports<'plural-ru'>;
}
declare module 'plural-ru/test/test.js' {
  declare module.exports: $Exports<'plural-ru/test/test'>;
}
