// flow-typed signature: bf76df48475fd68ca1ced122d7b93716
// flow-typed version: <<STUB>>/react-formal_v^0.23.1/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-formal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-formal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-formal/dev/dev' {
  declare module.exports: any;
}

declare module 'react-formal/docs/App' {
  declare module.exports: any;
}

declare module 'react-formal/docs/bundle' {
  declare module.exports: any;
}

declare module 'react-formal/docs/components/Codeblock' {
  declare module.exports: any;
}

declare module 'react-formal/docs/components/Console' {
  declare module.exports: any;
}

declare module 'react-formal/docs/loaders/jsx' {
  declare module.exports: any;
}

declare module 'react-formal/docs/loaders/metadata' {
  declare module.exports: any;
}

declare module 'react-formal/karma.conf' {
  declare module.exports: any;
}

declare module 'react-formal/lib/addInputType' {
  declare module.exports: any;
}

declare module 'react-formal/lib/config' {
  declare module.exports: any;
}

declare module 'react-formal/lib/errorManager' {
  declare module.exports: any;
}

declare module 'react-formal/lib/Field' {
  declare module.exports: any;
}

declare module 'react-formal/lib/Form' {
  declare module.exports: any;
}

declare module 'react-formal/lib/FormButton' {
  declare module.exports: any;
}

declare module 'react-formal/lib/FormContext' {
  declare module.exports: any;
}

declare module 'react-formal/lib/index' {
  declare module.exports: any;
}

declare module 'react-formal/lib/inputs/Bool' {
  declare module.exports: any;
}

declare module 'react-formal/lib/inputs/Date' {
  declare module.exports: any;
}

declare module 'react-formal/lib/inputs/index' {
  declare module.exports: any;
}

declare module 'react-formal/lib/inputs/Input' {
  declare module.exports: any;
}

declare module 'react-formal/lib/inputs/Number' {
  declare module.exports: any;
}

declare module 'react-formal/lib/inputs/Select' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/chainEvents' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/contextType' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/ErrorUtils' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/errToJSON' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/isNativeType' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/isReactComponent' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/parentContext' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/paths' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/registerWithContext' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/resolveFieldComponent' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/timeoutManager' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/types' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/uniqMessage' {
  declare module.exports: any;
}

declare module 'react-formal/lib/util/update' {
  declare module.exports: any;
}

declare module 'react-formal/lib/ValidationMessage' {
  declare module.exports: any;
}

declare module 'react-formal/lib/ValidationSummary' {
  declare module.exports: any;
}

declare module 'react-formal/src/addInputType' {
  declare module.exports: any;
}

declare module 'react-formal/src/config' {
  declare module.exports: any;
}

declare module 'react-formal/src/errorManager' {
  declare module.exports: any;
}

declare module 'react-formal/src/Field' {
  declare module.exports: any;
}

declare module 'react-formal/src/Form' {
  declare module.exports: any;
}

declare module 'react-formal/src/FormButton' {
  declare module.exports: any;
}

declare module 'react-formal/src/FormContext' {
  declare module.exports: any;
}

declare module 'react-formal/src/index' {
  declare module.exports: any;
}

declare module 'react-formal/src/inputs/Bool' {
  declare module.exports: any;
}

declare module 'react-formal/src/inputs/Date' {
  declare module.exports: any;
}

declare module 'react-formal/src/inputs/index' {
  declare module.exports: any;
}

declare module 'react-formal/src/inputs/Input' {
  declare module.exports: any;
}

declare module 'react-formal/src/inputs/Number' {
  declare module.exports: any;
}

declare module 'react-formal/src/inputs/Select' {
  declare module.exports: any;
}

declare module 'react-formal/src/util/chainEvents' {
  declare module.exports: any;
}

declare module 'react-formal/src/util/contextType' {
  declare module.exports: any;
}

declare module 'react-formal/src/util/ErrorUtils' {
  declare module.exports: any;
}

declare module 'react-formal/src/util/errToJSON' {
  declare module.exports: any;
}

declare module 'react-formal/src/util/isNativeType' {
  declare module.exports: any;
}

declare module 'react-formal/src/util/isReactComponent' {
  declare module.exports: any;
}

declare module 'react-formal/src/util/paths' {
  declare module.exports: any;
}

declare module 'react-formal/src/util/registerWithContext' {
  declare module.exports: any;
}

declare module 'react-formal/src/util/resolveFieldComponent' {
  declare module.exports: any;
}

declare module 'react-formal/src/util/timeoutManager' {
  declare module.exports: any;
}

declare module 'react-formal/src/util/types' {
  declare module.exports: any;
}

declare module 'react-formal/src/util/uniqMessage' {
  declare module.exports: any;
}

declare module 'react-formal/src/ValidationMessage' {
  declare module.exports: any;
}

declare module 'react-formal/src/ValidationSummary' {
  declare module.exports: any;
}

declare module 'react-formal/test' {
  declare module.exports: any;
}

declare module 'react-formal/test/Button' {
  declare module.exports: any;
}

declare module 'react-formal/test/context' {
  declare module.exports: any;
}

declare module 'react-formal/test/field' {
  declare module.exports: any;
}

declare module 'react-formal/test/form' {
  declare module.exports: any;
}

declare module 'react-formal/test/paths' {
  declare module.exports: any;
}

declare module 'react-formal/vendor/phantomjs-shim' {
  declare module.exports: any;
}

declare module 'react-formal/vendor/sinon-1.10.3' {
  declare module.exports: any;
}

declare module 'react-formal/webpack/dev.config' {
  declare module.exports: any;
}

declare module 'react-formal/webpack/docs.config' {
  declare module.exports: any;
}

declare module 'react-formal/webpack/test.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-formal/dev/dev.jsx' {
  declare module.exports: $Exports<'react-formal/dev/dev'>;
}
declare module 'react-formal/docs/App.js' {
  declare module.exports: $Exports<'react-formal/docs/App'>;
}
declare module 'react-formal/docs/bundle.js' {
  declare module.exports: $Exports<'react-formal/docs/bundle'>;
}
declare module 'react-formal/docs/components/Codeblock.js' {
  declare module.exports: $Exports<'react-formal/docs/components/Codeblock'>;
}
declare module 'react-formal/docs/components/Console.js' {
  declare module.exports: $Exports<'react-formal/docs/components/Console'>;
}
declare module 'react-formal/docs/loaders/jsx.js' {
  declare module.exports: $Exports<'react-formal/docs/loaders/jsx'>;
}
declare module 'react-formal/docs/loaders/metadata.js' {
  declare module.exports: $Exports<'react-formal/docs/loaders/metadata'>;
}
declare module 'react-formal/karma.conf.js' {
  declare module.exports: $Exports<'react-formal/karma.conf'>;
}
declare module 'react-formal/lib/addInputType.js' {
  declare module.exports: $Exports<'react-formal/lib/addInputType'>;
}
declare module 'react-formal/lib/config.js' {
  declare module.exports: $Exports<'react-formal/lib/config'>;
}
declare module 'react-formal/lib/errorManager.js' {
  declare module.exports: $Exports<'react-formal/lib/errorManager'>;
}
declare module 'react-formal/lib/Field.js' {
  declare module.exports: $Exports<'react-formal/lib/Field'>;
}
declare module 'react-formal/lib/Form.js' {
  declare module.exports: $Exports<'react-formal/lib/Form'>;
}
declare module 'react-formal/lib/FormButton.js' {
  declare module.exports: $Exports<'react-formal/lib/FormButton'>;
}
declare module 'react-formal/lib/FormContext.js' {
  declare module.exports: $Exports<'react-formal/lib/FormContext'>;
}
declare module 'react-formal/lib/index.js' {
  declare module.exports: $Exports<'react-formal/lib/index'>;
}
declare module 'react-formal/lib/inputs/Bool.js' {
  declare module.exports: $Exports<'react-formal/lib/inputs/Bool'>;
}
declare module 'react-formal/lib/inputs/Date.js' {
  declare module.exports: $Exports<'react-formal/lib/inputs/Date'>;
}
declare module 'react-formal/lib/inputs/index.js' {
  declare module.exports: $Exports<'react-formal/lib/inputs/index'>;
}
declare module 'react-formal/lib/inputs/Input.js' {
  declare module.exports: $Exports<'react-formal/lib/inputs/Input'>;
}
declare module 'react-formal/lib/inputs/Number.js' {
  declare module.exports: $Exports<'react-formal/lib/inputs/Number'>;
}
declare module 'react-formal/lib/inputs/Select.js' {
  declare module.exports: $Exports<'react-formal/lib/inputs/Select'>;
}
declare module 'react-formal/lib/util/chainEvents.js' {
  declare module.exports: $Exports<'react-formal/lib/util/chainEvents'>;
}
declare module 'react-formal/lib/util/contextType.js' {
  declare module.exports: $Exports<'react-formal/lib/util/contextType'>;
}
declare module 'react-formal/lib/util/ErrorUtils.js' {
  declare module.exports: $Exports<'react-formal/lib/util/ErrorUtils'>;
}
declare module 'react-formal/lib/util/errToJSON.js' {
  declare module.exports: $Exports<'react-formal/lib/util/errToJSON'>;
}
declare module 'react-formal/lib/util/isNativeType.js' {
  declare module.exports: $Exports<'react-formal/lib/util/isNativeType'>;
}
declare module 'react-formal/lib/util/isReactComponent.js' {
  declare module.exports: $Exports<'react-formal/lib/util/isReactComponent'>;
}
declare module 'react-formal/lib/util/parentContext.js' {
  declare module.exports: $Exports<'react-formal/lib/util/parentContext'>;
}
declare module 'react-formal/lib/util/paths.js' {
  declare module.exports: $Exports<'react-formal/lib/util/paths'>;
}
declare module 'react-formal/lib/util/registerWithContext.js' {
  declare module.exports: $Exports<'react-formal/lib/util/registerWithContext'>;
}
declare module 'react-formal/lib/util/resolveFieldComponent.js' {
  declare module.exports: $Exports<'react-formal/lib/util/resolveFieldComponent'>;
}
declare module 'react-formal/lib/util/timeoutManager.js' {
  declare module.exports: $Exports<'react-formal/lib/util/timeoutManager'>;
}
declare module 'react-formal/lib/util/types.js' {
  declare module.exports: $Exports<'react-formal/lib/util/types'>;
}
declare module 'react-formal/lib/util/uniqMessage.js' {
  declare module.exports: $Exports<'react-formal/lib/util/uniqMessage'>;
}
declare module 'react-formal/lib/util/update.js' {
  declare module.exports: $Exports<'react-formal/lib/util/update'>;
}
declare module 'react-formal/lib/ValidationMessage.js' {
  declare module.exports: $Exports<'react-formal/lib/ValidationMessage'>;
}
declare module 'react-formal/lib/ValidationSummary.js' {
  declare module.exports: $Exports<'react-formal/lib/ValidationSummary'>;
}
declare module 'react-formal/src/addInputType.js' {
  declare module.exports: $Exports<'react-formal/src/addInputType'>;
}
declare module 'react-formal/src/config.js' {
  declare module.exports: $Exports<'react-formal/src/config'>;
}
declare module 'react-formal/src/errorManager.js' {
  declare module.exports: $Exports<'react-formal/src/errorManager'>;
}
declare module 'react-formal/src/Field.js' {
  declare module.exports: $Exports<'react-formal/src/Field'>;
}
declare module 'react-formal/src/Form.js' {
  declare module.exports: $Exports<'react-formal/src/Form'>;
}
declare module 'react-formal/src/FormButton.js' {
  declare module.exports: $Exports<'react-formal/src/FormButton'>;
}
declare module 'react-formal/src/FormContext.js' {
  declare module.exports: $Exports<'react-formal/src/FormContext'>;
}
declare module 'react-formal/src/index.js' {
  declare module.exports: $Exports<'react-formal/src/index'>;
}
declare module 'react-formal/src/inputs/Bool.js' {
  declare module.exports: $Exports<'react-formal/src/inputs/Bool'>;
}
declare module 'react-formal/src/inputs/Date.js' {
  declare module.exports: $Exports<'react-formal/src/inputs/Date'>;
}
declare module 'react-formal/src/inputs/index.js' {
  declare module.exports: $Exports<'react-formal/src/inputs/index'>;
}
declare module 'react-formal/src/inputs/Input.js' {
  declare module.exports: $Exports<'react-formal/src/inputs/Input'>;
}
declare module 'react-formal/src/inputs/Number.js' {
  declare module.exports: $Exports<'react-formal/src/inputs/Number'>;
}
declare module 'react-formal/src/inputs/Select.js' {
  declare module.exports: $Exports<'react-formal/src/inputs/Select'>;
}
declare module 'react-formal/src/util/chainEvents.js' {
  declare module.exports: $Exports<'react-formal/src/util/chainEvents'>;
}
declare module 'react-formal/src/util/contextType.js' {
  declare module.exports: $Exports<'react-formal/src/util/contextType'>;
}
declare module 'react-formal/src/util/ErrorUtils.js' {
  declare module.exports: $Exports<'react-formal/src/util/ErrorUtils'>;
}
declare module 'react-formal/src/util/errToJSON.js' {
  declare module.exports: $Exports<'react-formal/src/util/errToJSON'>;
}
declare module 'react-formal/src/util/isNativeType.js' {
  declare module.exports: $Exports<'react-formal/src/util/isNativeType'>;
}
declare module 'react-formal/src/util/isReactComponent.js' {
  declare module.exports: $Exports<'react-formal/src/util/isReactComponent'>;
}
declare module 'react-formal/src/util/paths.js' {
  declare module.exports: $Exports<'react-formal/src/util/paths'>;
}
declare module 'react-formal/src/util/registerWithContext.js' {
  declare module.exports: $Exports<'react-formal/src/util/registerWithContext'>;
}
declare module 'react-formal/src/util/resolveFieldComponent.js' {
  declare module.exports: $Exports<'react-formal/src/util/resolveFieldComponent'>;
}
declare module 'react-formal/src/util/timeoutManager.js' {
  declare module.exports: $Exports<'react-formal/src/util/timeoutManager'>;
}
declare module 'react-formal/src/util/types.js' {
  declare module.exports: $Exports<'react-formal/src/util/types'>;
}
declare module 'react-formal/src/util/uniqMessage.js' {
  declare module.exports: $Exports<'react-formal/src/util/uniqMessage'>;
}
declare module 'react-formal/src/ValidationMessage.js' {
  declare module.exports: $Exports<'react-formal/src/ValidationMessage'>;
}
declare module 'react-formal/src/ValidationSummary.js' {
  declare module.exports: $Exports<'react-formal/src/ValidationSummary'>;
}
declare module 'react-formal/test.js' {
  declare module.exports: $Exports<'react-formal/test'>;
}
declare module 'react-formal/test/Button.js' {
  declare module.exports: $Exports<'react-formal/test/Button'>;
}
declare module 'react-formal/test/context.js' {
  declare module.exports: $Exports<'react-formal/test/context'>;
}
declare module 'react-formal/test/field.js' {
  declare module.exports: $Exports<'react-formal/test/field'>;
}
declare module 'react-formal/test/form.js' {
  declare module.exports: $Exports<'react-formal/test/form'>;
}
declare module 'react-formal/test/paths.js' {
  declare module.exports: $Exports<'react-formal/test/paths'>;
}
declare module 'react-formal/vendor/phantomjs-shim.js' {
  declare module.exports: $Exports<'react-formal/vendor/phantomjs-shim'>;
}
declare module 'react-formal/vendor/sinon-1.10.3.js' {
  declare module.exports: $Exports<'react-formal/vendor/sinon-1.10.3'>;
}
declare module 'react-formal/webpack/dev.config.js' {
  declare module.exports: $Exports<'react-formal/webpack/dev.config'>;
}
declare module 'react-formal/webpack/docs.config.js' {
  declare module.exports: $Exports<'react-formal/webpack/docs.config'>;
}
declare module 'react-formal/webpack/test.config.js' {
  declare module.exports: $Exports<'react-formal/webpack/test.config'>;
}
