// flow-typed signature: d7e6552b0c56357ac9454854fd47b3a1
// flow-typed version: <<STUB>>/react-headroom_v^2.1.3/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-headroom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-headroom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-headroom/dist/index' {
  declare module.exports: any;
}

declare module 'react-headroom/dist/shouldUpdate' {
  declare module.exports: any;
}

declare module 'react-headroom/src/index' {
  declare module.exports: any;
}

declare module 'react-headroom/src/shouldUpdate' {
  declare module.exports: any;
}

declare module 'react-headroom/test/calc' {
  declare module.exports: any;
}

declare module 'react-headroom/www/gatsby-browser' {
  declare module.exports: any;
}

declare module 'react-headroom/www/gatsby-config' {
  declare module.exports: any;
}

declare module 'react-headroom/www/gatsby-node' {
  declare module.exports: any;
}

declare module 'react-headroom/www/html' {
  declare module.exports: any;
}

declare module 'react-headroom/www/page-templates/index' {
  declare module.exports: any;
}

declare module 'react-headroom/www/public/app-538f48287d38855964ff' {
  declare module.exports: any;
}

declare module 'react-headroom/www/public/app-d101248fa8e3e1384752' {
  declare module.exports: any;
}

declare module 'react-headroom/www/public/commons-1473415785ec677aa9d6' {
  declare module.exports: any;
}

declare module 'react-headroom/www/public/commons-d987a46b285be4f020d7' {
  declare module.exports: any;
}

declare module 'react-headroom/www/public/page-component---page-templates-index-js-c5c22f9a27bfe52c4045' {
  declare module.exports: any;
}

declare module 'react-headroom/www/public/page-component---page-templates-index-js-e756f20cd56cf1e40beb' {
  declare module.exports: any;
}

declare module 'react-headroom/www/public/path---index-73cb425199abe0b911f8' {
  declare module.exports: any;
}

declare module 'react-headroom/www/public/sw' {
  declare module.exports: any;
}

declare module 'react-headroom/www/utils/typography' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-headroom/dist/index.js' {
  declare module.exports: $Exports<'react-headroom/dist/index'>;
}
declare module 'react-headroom/dist/shouldUpdate.js' {
  declare module.exports: $Exports<'react-headroom/dist/shouldUpdate'>;
}
declare module 'react-headroom/src/index.js' {
  declare module.exports: $Exports<'react-headroom/src/index'>;
}
declare module 'react-headroom/src/shouldUpdate.js' {
  declare module.exports: $Exports<'react-headroom/src/shouldUpdate'>;
}
declare module 'react-headroom/test/calc.js' {
  declare module.exports: $Exports<'react-headroom/test/calc'>;
}
declare module 'react-headroom/www/gatsby-browser.js' {
  declare module.exports: $Exports<'react-headroom/www/gatsby-browser'>;
}
declare module 'react-headroom/www/gatsby-config.js' {
  declare module.exports: $Exports<'react-headroom/www/gatsby-config'>;
}
declare module 'react-headroom/www/gatsby-node.js' {
  declare module.exports: $Exports<'react-headroom/www/gatsby-node'>;
}
declare module 'react-headroom/www/html.js' {
  declare module.exports: $Exports<'react-headroom/www/html'>;
}
declare module 'react-headroom/www/page-templates/index.js' {
  declare module.exports: $Exports<'react-headroom/www/page-templates/index'>;
}
declare module 'react-headroom/www/public/app-538f48287d38855964ff.js' {
  declare module.exports: $Exports<'react-headroom/www/public/app-538f48287d38855964ff'>;
}
declare module 'react-headroom/www/public/app-d101248fa8e3e1384752.js' {
  declare module.exports: $Exports<'react-headroom/www/public/app-d101248fa8e3e1384752'>;
}
declare module 'react-headroom/www/public/commons-1473415785ec677aa9d6.js' {
  declare module.exports: $Exports<'react-headroom/www/public/commons-1473415785ec677aa9d6'>;
}
declare module 'react-headroom/www/public/commons-d987a46b285be4f020d7.js' {
  declare module.exports: $Exports<'react-headroom/www/public/commons-d987a46b285be4f020d7'>;
}
declare module 'react-headroom/www/public/page-component---page-templates-index-js-c5c22f9a27bfe52c4045.js' {
  declare module.exports: $Exports<'react-headroom/www/public/page-component---page-templates-index-js-c5c22f9a27bfe52c4045'>;
}
declare module 'react-headroom/www/public/page-component---page-templates-index-js-e756f20cd56cf1e40beb.js' {
  declare module.exports: $Exports<'react-headroom/www/public/page-component---page-templates-index-js-e756f20cd56cf1e40beb'>;
}
declare module 'react-headroom/www/public/path---index-73cb425199abe0b911f8.js' {
  declare module.exports: $Exports<'react-headroom/www/public/path---index-73cb425199abe0b911f8'>;
}
declare module 'react-headroom/www/public/sw.js' {
  declare module.exports: $Exports<'react-headroom/www/public/sw'>;
}
declare module 'react-headroom/www/utils/typography.js' {
  declare module.exports: $Exports<'react-headroom/www/utils/typography'>;
}
