// flow-typed signature: 5a68b49d6246022b30e3d82886c7c0ff
// flow-typed version: <<STUB>>/reading-time_v^1.1.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reading-time'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'reading-time' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reading-time/lib/reading-time' {
  declare module.exports: any;
}

declare module 'reading-time/lib/stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reading-time/index' {
  declare module.exports: $Exports<'reading-time'>;
}
declare module 'reading-time/index.js' {
  declare module.exports: $Exports<'reading-time'>;
}
declare module 'reading-time/lib/reading-time.js' {
  declare module.exports: $Exports<'reading-time/lib/reading-time'>;
}
declare module 'reading-time/lib/stream.js' {
  declare module.exports: $Exports<'reading-time/lib/stream'>;
}
