// flow-typed signature: 7fd5a4baf33bc58723085797a71b574a
// flow-typed version: <<STUB>>/sitemap_v^1.8.2/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sitemap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sitemap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sitemap/lib/errors' {
  declare module.exports: any;
}

declare module 'sitemap/lib/sitemap' {
  declare module.exports: any;
}

declare module 'sitemap/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sitemap/index' {
  declare module.exports: $Exports<'sitemap'>;
}
declare module 'sitemap/index.js' {
  declare module.exports: $Exports<'sitemap'>;
}
declare module 'sitemap/lib/errors.js' {
  declare module.exports: $Exports<'sitemap/lib/errors'>;
}
declare module 'sitemap/lib/sitemap.js' {
  declare module.exports: $Exports<'sitemap/lib/sitemap'>;
}
declare module 'sitemap/lib/utils.js' {
  declare module.exports: $Exports<'sitemap/lib/utils'>;
}
