// flow-typed signature: 803ec81964673c29f5e2707d9bb3a6db
// flow-typed version: <<STUB>>/smoothscroll_v^0.2.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'smoothscroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'smoothscroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'smoothscroll/smoothscroll' {
  declare module.exports: any;
}

declare module 'smoothscroll/smoothscroll.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'smoothscroll/smoothscroll.js' {
  declare module.exports: $Exports<'smoothscroll/smoothscroll'>;
}
declare module 'smoothscroll/smoothscroll.min.js' {
  declare module.exports: $Exports<'smoothscroll/smoothscroll.min'>;
}
