// flow-typed signature: b37b4f5125ee8a3f2612d777c50eea37
// flow-typed version: <<STUB>>/stylelint-config-primer_v^1.3.0/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-config-primer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-config-primer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'stylelint-config-primer/index' {
  declare module.exports: $Exports<'stylelint-config-primer'>;
}
declare module 'stylelint-config-primer/index.js' {
  declare module.exports: $Exports<'stylelint-config-primer'>;
}
