// flow-typed signature: 5a097b7ef539504c0b85873451b8da3d
// flow-typed version: <<STUB>>/tachyons-sass_v^4.5.5/flow_v0.35.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tachyons-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tachyons-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tachyons-sass/build' {
  declare module.exports: any;
}

declare module 'tachyons-sass/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tachyons-sass/build.js' {
  declare module.exports: $Exports<'tachyons-sass/build'>;
}
declare module 'tachyons-sass/test.js' {
  declare module.exports: $Exports<'tachyons-sass/test'>;
}
