// flow-typed signature: 5920a89cc0078c38adfc3f54ae9588e0
// flow-typed version: <<STUB>>/toml_v^2.3.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'toml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'toml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'toml/benchmark' {
  declare module.exports: any;
}

declare module 'toml/lib/compiler' {
  declare module.exports: any;
}

declare module 'toml/lib/parser' {
  declare module.exports: any;
}

declare module 'toml/test/smoke' {
  declare module.exports: any;
}

declare module 'toml/test/test_toml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'toml/benchmark.js' {
  declare module.exports: $Exports<'toml/benchmark'>;
}
declare module 'toml/index' {
  declare module.exports: $Exports<'toml'>;
}
declare module 'toml/index.js' {
  declare module.exports: $Exports<'toml'>;
}
declare module 'toml/lib/compiler.js' {
  declare module.exports: $Exports<'toml/lib/compiler'>;
}
declare module 'toml/lib/parser.js' {
  declare module.exports: $Exports<'toml/lib/parser'>;
}
declare module 'toml/test/smoke.js' {
  declare module.exports: $Exports<'toml/test/smoke'>;
}
declare module 'toml/test/test_toml.js' {
  declare module.exports: $Exports<'toml/test/test_toml'>;
}
