// flow-typed signature: 33937d6dbed25e9e6a8bbbdbda39bb58
// flow-typed version: <<STUB>>/validate-commit-msg_v^2.8.2/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'validate-commit-msg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'validate-commit-msg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'validate-commit-msg/index' {
  declare module.exports: $Exports<'validate-commit-msg'>;
}
declare module 'validate-commit-msg/index.js' {
  declare module.exports: $Exports<'validate-commit-msg'>;
}
